POST http://localhost:6000/auth/login
Content-Type: application/json

{
    "brugerEmail": "sasha@gmail.com",
    "brugerPassword": "secret"
}
###

GET http://localhost:6000/auth/logout

###

GET http://localhost:6000/auth/loggedin






