POST https://gaader-server.herokuapp.com/auth/login
Content-Type: application/json

{
    "brugerEmail": "kumu@gmail.com",
    "brugerPassword": "secret"
}
###

GET https://gaader-server.herokuapp.com/auth/logout

###

GET https://gaader-server.herokuapp.com/auth/loggedin






