GET https://gaader-server.herokuapp.com/admin/brugere

###

GET https://gaader-server.herokuapp.com/admin/brugere/5ee7482163f26e47bc06818

###

POST https://gaader-server.herokuapp.com/admin/brugere
Content-Type: application/json

{
    "brugerName": "Sissi",
    "brugerEmail": "sissi@gmail.com",
    "brugerPassword": "secret"
}

###
PATCH  https://gaader-server.herokuapp.com/admin/brugere/5ee1d8d49b11f74474653c15
Content-Type: application/json

{
    "brugerName": "Jesper",
    "brugerEmail": "jesper@gmail.com",
    "brugerPassword": "secret"
}

###
DELETE https://gaader-server.herokuapp.com/admin/brugere/5ee1dab7756a9e3c4c8ef6b2

