GET https://gaader-server.herokuapp.com/gaader

###

GET https://gaader-server.herokuapp.com/gaader/5ee0ce06b9d0211f789cf105

###

POST https://gaader-server.herokuapp.com/gaader/admin
Content-Type: application/json

{
    "gaade": " En mand har et firkantet hus. Hver side vender mod syd. En bjørn går forbi. Hvilken farve har den?",
    "gaadeSvar": "hvid"
}


###
PATCH  https://gaader-server.herokuapp.com/gaader/admin/5eec6c0012f7be001727b437
Content-Type: application/json

{
    "gaade": "Solen er rød",
    "gaadeSvar": "nej den er varm lige her"
}

###
DELETE https://gaader-server.herokuapp.com/gaader/admin/5eeb269382149900178d0a2d
